// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"fmt"
	"strings"
)

const (
	// ClusterClientSessionFieldsId is a ClusterClientSessionFields of type Id.
	ClusterClientSessionFieldsId ClusterClientSessionFields = iota
	// ClusterClientSessionFieldsUuid is a ClusterClientSessionFields of type Uuid.
	ClusterClientSessionFieldsUuid
	// ClusterClientSessionFieldsClusterClientTokenUuid is a ClusterClientSessionFields of type Cluster_client_token_uuid.
	ClusterClientSessionFieldsClusterClientTokenUuid
	// ClusterClientSessionFieldsClusterUuid is a ClusterClientSessionFields of type Cluster_uuid.
	ClusterClientSessionFieldsClusterUuid
	// ClusterClientSessionFieldsToken is a ClusterClientSessionFields of type Token.
	ClusterClientSessionFieldsToken
	// ClusterClientSessionFieldsIssuedAtTime is a ClusterClientSessionFields of type Issued_at_time.
	ClusterClientSessionFieldsIssuedAtTime
	// ClusterClientSessionFieldsExpirationTime is a ClusterClientSessionFields of type Expiration_time.
	ClusterClientSessionFieldsExpirationTime
	// ClusterClientSessionFieldsCreated is a ClusterClientSessionFields of type Created.
	ClusterClientSessionFieldsCreated
	// ClusterClientSessionFieldsUpdated is a ClusterClientSessionFields of type Updated.
	ClusterClientSessionFieldsUpdated
)

var ErrInvalidClusterClientSessionFields = fmt.Errorf("not a valid ClusterClientSessionFields, try [%s]", strings.Join(_ClusterClientSessionFieldsNames, ", "))

const _ClusterClientSessionFieldsName = "iduuidcluster_client_token_uuidcluster_uuidtokenissued_at_timeexpiration_timecreatedupdated"

var _ClusterClientSessionFieldsNames = []string{
	_ClusterClientSessionFieldsName[0:2],
	_ClusterClientSessionFieldsName[2:6],
	_ClusterClientSessionFieldsName[6:31],
	_ClusterClientSessionFieldsName[31:43],
	_ClusterClientSessionFieldsName[43:48],
	_ClusterClientSessionFieldsName[48:62],
	_ClusterClientSessionFieldsName[62:77],
	_ClusterClientSessionFieldsName[77:84],
	_ClusterClientSessionFieldsName[84:91],
}

// ClusterClientSessionFieldsNames returns a list of possible string values of ClusterClientSessionFields.
func ClusterClientSessionFieldsNames() []string {
	tmp := make([]string, len(_ClusterClientSessionFieldsNames))
	copy(tmp, _ClusterClientSessionFieldsNames)
	return tmp
}

var _ClusterClientSessionFieldsMap = map[ClusterClientSessionFields]string{
	ClusterClientSessionFieldsId:                     _ClusterClientSessionFieldsName[0:2],
	ClusterClientSessionFieldsUuid:                   _ClusterClientSessionFieldsName[2:6],
	ClusterClientSessionFieldsClusterClientTokenUuid: _ClusterClientSessionFieldsName[6:31],
	ClusterClientSessionFieldsClusterUuid:            _ClusterClientSessionFieldsName[31:43],
	ClusterClientSessionFieldsToken:                  _ClusterClientSessionFieldsName[43:48],
	ClusterClientSessionFieldsIssuedAtTime:           _ClusterClientSessionFieldsName[48:62],
	ClusterClientSessionFieldsExpirationTime:         _ClusterClientSessionFieldsName[62:77],
	ClusterClientSessionFieldsCreated:                _ClusterClientSessionFieldsName[77:84],
	ClusterClientSessionFieldsUpdated:                _ClusterClientSessionFieldsName[84:91],
}

// String implements the Stringer interface.
func (x ClusterClientSessionFields) String() string {
	if str, ok := _ClusterClientSessionFieldsMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ClusterClientSessionFields(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ClusterClientSessionFields) IsValid() bool {
	_, ok := _ClusterClientSessionFieldsMap[x]
	return ok
}

var _ClusterClientSessionFieldsValue = map[string]ClusterClientSessionFields{
	_ClusterClientSessionFieldsName[0:2]:                    ClusterClientSessionFieldsId,
	strings.ToLower(_ClusterClientSessionFieldsName[0:2]):   ClusterClientSessionFieldsId,
	_ClusterClientSessionFieldsName[2:6]:                    ClusterClientSessionFieldsUuid,
	strings.ToLower(_ClusterClientSessionFieldsName[2:6]):   ClusterClientSessionFieldsUuid,
	_ClusterClientSessionFieldsName[6:31]:                   ClusterClientSessionFieldsClusterClientTokenUuid,
	strings.ToLower(_ClusterClientSessionFieldsName[6:31]):  ClusterClientSessionFieldsClusterClientTokenUuid,
	_ClusterClientSessionFieldsName[31:43]:                  ClusterClientSessionFieldsClusterUuid,
	strings.ToLower(_ClusterClientSessionFieldsName[31:43]): ClusterClientSessionFieldsClusterUuid,
	_ClusterClientSessionFieldsName[43:48]:                  ClusterClientSessionFieldsToken,
	strings.ToLower(_ClusterClientSessionFieldsName[43:48]): ClusterClientSessionFieldsToken,
	_ClusterClientSessionFieldsName[48:62]:                  ClusterClientSessionFieldsIssuedAtTime,
	strings.ToLower(_ClusterClientSessionFieldsName[48:62]): ClusterClientSessionFieldsIssuedAtTime,
	_ClusterClientSessionFieldsName[62:77]:                  ClusterClientSessionFieldsExpirationTime,
	strings.ToLower(_ClusterClientSessionFieldsName[62:77]): ClusterClientSessionFieldsExpirationTime,
	_ClusterClientSessionFieldsName[77:84]:                  ClusterClientSessionFieldsCreated,
	strings.ToLower(_ClusterClientSessionFieldsName[77:84]): ClusterClientSessionFieldsCreated,
	_ClusterClientSessionFieldsName[84:91]:                  ClusterClientSessionFieldsUpdated,
	strings.ToLower(_ClusterClientSessionFieldsName[84:91]): ClusterClientSessionFieldsUpdated,
}

// ParseClusterClientSessionFields attempts to convert a string to a ClusterClientSessionFields.
func ParseClusterClientSessionFields(name string) (ClusterClientSessionFields, error) {
	if x, ok := _ClusterClientSessionFieldsValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ClusterClientSessionFieldsValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return ClusterClientSessionFields(0), fmt.Errorf("%s is %w", name, ErrInvalidClusterClientSessionFields)
}
