// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"fmt"
	"strings"
)

const (
	// ClusterClientTokenFieldsId is a ClusterClientTokenFields of type Id.
	ClusterClientTokenFieldsId ClusterClientTokenFields = iota
	// ClusterClientTokenFieldsUuid is a ClusterClientTokenFields of type Uuid.
	ClusterClientTokenFieldsUuid
	// ClusterClientTokenFieldsName is a ClusterClientTokenFields of type Name.
	ClusterClientTokenFieldsName
	// ClusterClientTokenFieldsSummary is a ClusterClientTokenFields of type Summary.
	ClusterClientTokenFieldsSummary
	// ClusterClientTokenFieldsClusterUuid is a ClusterClientTokenFields of type Cluster_uuid.
	ClusterClientTokenFieldsClusterUuid
	// ClusterClientTokenFieldsToken is a ClusterClientTokenFields of type Token.
	ClusterClientTokenFieldsToken
	// ClusterClientTokenFieldsIssuedAtTime is a ClusterClientTokenFields of type Issued_at_time.
	ClusterClientTokenFieldsIssuedAtTime
	// ClusterClientTokenFieldsExpirationTime is a ClusterClientTokenFields of type Expiration_time.
	ClusterClientTokenFieldsExpirationTime
	// ClusterClientTokenFieldsCreated is a ClusterClientTokenFields of type Created.
	ClusterClientTokenFieldsCreated
	// ClusterClientTokenFieldsUpdated is a ClusterClientTokenFields of type Updated.
	ClusterClientTokenFieldsUpdated
)

var ErrInvalidClusterClientTokenFields = fmt.Errorf("not a valid ClusterClientTokenFields, try [%s]", strings.Join(_ClusterClientTokenFieldsNames, ", "))

const _ClusterClientTokenFieldsName = "iduuidnamesummarycluster_uuidtokenissued_at_timeexpiration_timecreatedupdated"

var _ClusterClientTokenFieldsNames = []string{
	_ClusterClientTokenFieldsName[0:2],
	_ClusterClientTokenFieldsName[2:6],
	_ClusterClientTokenFieldsName[6:10],
	_ClusterClientTokenFieldsName[10:17],
	_ClusterClientTokenFieldsName[17:29],
	_ClusterClientTokenFieldsName[29:34],
	_ClusterClientTokenFieldsName[34:48],
	_ClusterClientTokenFieldsName[48:63],
	_ClusterClientTokenFieldsName[63:70],
	_ClusterClientTokenFieldsName[70:77],
}

// ClusterClientTokenFieldsNames returns a list of possible string values of ClusterClientTokenFields.
func ClusterClientTokenFieldsNames() []string {
	tmp := make([]string, len(_ClusterClientTokenFieldsNames))
	copy(tmp, _ClusterClientTokenFieldsNames)
	return tmp
}

var _ClusterClientTokenFieldsMap = map[ClusterClientTokenFields]string{
	ClusterClientTokenFieldsId:             _ClusterClientTokenFieldsName[0:2],
	ClusterClientTokenFieldsUuid:           _ClusterClientTokenFieldsName[2:6],
	ClusterClientTokenFieldsName:           _ClusterClientTokenFieldsName[6:10],
	ClusterClientTokenFieldsSummary:        _ClusterClientTokenFieldsName[10:17],
	ClusterClientTokenFieldsClusterUuid:    _ClusterClientTokenFieldsName[17:29],
	ClusterClientTokenFieldsToken:          _ClusterClientTokenFieldsName[29:34],
	ClusterClientTokenFieldsIssuedAtTime:   _ClusterClientTokenFieldsName[34:48],
	ClusterClientTokenFieldsExpirationTime: _ClusterClientTokenFieldsName[48:63],
	ClusterClientTokenFieldsCreated:        _ClusterClientTokenFieldsName[63:70],
	ClusterClientTokenFieldsUpdated:        _ClusterClientTokenFieldsName[70:77],
}

// String implements the Stringer interface.
func (x ClusterClientTokenFields) String() string {
	if str, ok := _ClusterClientTokenFieldsMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ClusterClientTokenFields(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ClusterClientTokenFields) IsValid() bool {
	_, ok := _ClusterClientTokenFieldsMap[x]
	return ok
}

var _ClusterClientTokenFieldsValue = map[string]ClusterClientTokenFields{
	_ClusterClientTokenFieldsName[0:2]:                    ClusterClientTokenFieldsId,
	strings.ToLower(_ClusterClientTokenFieldsName[0:2]):   ClusterClientTokenFieldsId,
	_ClusterClientTokenFieldsName[2:6]:                    ClusterClientTokenFieldsUuid,
	strings.ToLower(_ClusterClientTokenFieldsName[2:6]):   ClusterClientTokenFieldsUuid,
	_ClusterClientTokenFieldsName[6:10]:                   ClusterClientTokenFieldsName,
	strings.ToLower(_ClusterClientTokenFieldsName[6:10]):  ClusterClientTokenFieldsName,
	_ClusterClientTokenFieldsName[10:17]:                  ClusterClientTokenFieldsSummary,
	strings.ToLower(_ClusterClientTokenFieldsName[10:17]): ClusterClientTokenFieldsSummary,
	_ClusterClientTokenFieldsName[17:29]:                  ClusterClientTokenFieldsClusterUuid,
	strings.ToLower(_ClusterClientTokenFieldsName[17:29]): ClusterClientTokenFieldsClusterUuid,
	_ClusterClientTokenFieldsName[29:34]:                  ClusterClientTokenFieldsToken,
	strings.ToLower(_ClusterClientTokenFieldsName[29:34]): ClusterClientTokenFieldsToken,
	_ClusterClientTokenFieldsName[34:48]:                  ClusterClientTokenFieldsIssuedAtTime,
	strings.ToLower(_ClusterClientTokenFieldsName[34:48]): ClusterClientTokenFieldsIssuedAtTime,
	_ClusterClientTokenFieldsName[48:63]:                  ClusterClientTokenFieldsExpirationTime,
	strings.ToLower(_ClusterClientTokenFieldsName[48:63]): ClusterClientTokenFieldsExpirationTime,
	_ClusterClientTokenFieldsName[63:70]:                  ClusterClientTokenFieldsCreated,
	strings.ToLower(_ClusterClientTokenFieldsName[63:70]): ClusterClientTokenFieldsCreated,
	_ClusterClientTokenFieldsName[70:77]:                  ClusterClientTokenFieldsUpdated,
	strings.ToLower(_ClusterClientTokenFieldsName[70:77]): ClusterClientTokenFieldsUpdated,
}

// ParseClusterClientTokenFields attempts to convert a string to a ClusterClientTokenFields.
func ParseClusterClientTokenFields(name string) (ClusterClientTokenFields, error) {
	if x, ok := _ClusterClientTokenFieldsValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ClusterClientTokenFieldsValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return ClusterClientTokenFields(0), fmt.Errorf("%s is %w", name, ErrInvalidClusterClientTokenFields)
}
