CREATE TABLE IF NOT EXISTS `cluster` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uuid` char(32) NOT NULL,
  `name` varchar(255) NOT NULL,
  `summary` varchar(255) DEFAULT NULL,
  `created` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;

ALTER TABLE IF EXISTS `cluster` 
  CONVERT TO CHARACTER SET utf8mb4
;

ALTER TABLE IF EXISTS `cluster` 
  MODIFY IF EXISTS `created` datetime DEFAULT CURRENT_TIMESTAMP,
  MODIFY IF EXISTS `updated` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
;

ALTER TABLE IF EXISTS `cluster`
  -- add unique
  ADD CONSTRAINT `uuid` UNIQUE IF NOT EXISTS (`uuid`) 
;
