// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "url": "https://claion.co.kr",
            "email": "jaehoon@claion.co.kr"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/client/auth": {
            "post": {
                "description": "auth client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/client"
                ],
                "parameters": [
                    {
                        "description": "Auth",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.Auth"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "AccessTokenResponse": {
                                "type": "object"
                            },
                            "x-sudory-client-token": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/client/service": {
            "get": {
                "security": [
                    {
                        "ClientAuthorization": []
                    }
                ],
                "description": "get []Service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/client"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "count limit of ServiceResponse",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/client.ServiceResponse"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ClientAuthorization": []
                    }
                ],
                "description": "update a service status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/client"
                ],
                "parameters": [
                    {
                        "description": "ServiceStatus",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.ServiceStatus"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/cluster": {
            "get": {
                "description": "Find clusters",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/cluster"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "query  github.com/claion-org/claiflow/pkg/server/database/vanilla/stmt/README.md",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order  github.com/claion-org/claiflow/pkg/server/database/vanilla/stmt/README.md",
                        "name": "o",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "paging github.com/claion-org/claiflow/pkg/server/database/vanilla/stmt/README.md",
                        "name": "p",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cluster.Cluster"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/cluster"
                ],
                "parameters": [
                    {
                        "description": "Create",
                        "name": "cluster",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cluster.Create"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cluster.Cluster"
                        }
                    }
                }
            }
        },
        "/api/v1/cluster/{cluster_uuid}/service": {
            "post": {
                "description": "Create a Service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/service"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "cluster UUID",
                        "name": "cluster_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create",
                        "name": "service",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.Create"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.ServiceResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/cluster/{cluster_uuid}/service/{uuid}": {
            "get": {
                "description": "Get a Service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/service"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "cluster UUID",
                        "name": "cluster_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ServiceResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/cluster/{cluster_uuid}/service/{uuid}/result": {
            "get": {
                "description": "Get a Service Result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/service"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "cluster UUID",
                        "name": "cluster_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ResultResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/cluster/{cluster_uuid}/session/alive": {
            "get": {
                "description": "Check Alive a Cluster Client Session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/cluster"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "cluster_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cluster.ClusterClientSessionStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/cluster/{uuid}": {
            "get": {
                "description": "Get a cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/cluster"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cluster.Cluster"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/cluster"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update",
                        "name": "cluster",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cluster.Update"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cluster.Cluster"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/cluster"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/cluster_token": {
            "get": {
                "description": "Find Cluster Client Tokens",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/cluster_token"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "query  github.com/claion-org/claiflow/pkg/server/database/vanilla/stmt/README.md",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order  github.com/claion-org/claiflow/pkg/server/database/vanilla/stmt/README.md",
                        "name": "o",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "paging github.com/claion-org/claiflow/pkg/server/database/vanilla/stmt/README.md",
                        "name": "p",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cluster_client_token.ClusterClientToken"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Cluster Client Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/cluster_token"
                ],
                "parameters": [
                    {
                        "description": "Create",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cluster_client_token.Create"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cluster_client_token.ClusterClientToken"
                        }
                    }
                }
            }
        },
        "/api/v1/cluster_token/{uuid}": {
            "get": {
                "description": "Get a Cluster Client Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/cluster_token"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ClusterClientToken Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cluster_client_token.ClusterClientToken"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a Cluster Client Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/cluster_token"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ClusterClientToken UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cluster_client_token.Update"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cluster_client_token.ClusterClientToken"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a Cluster Client Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/cluster_token"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ClusterClientToken UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/cluster_token/{uuid}/expire": {
            "put": {
                "description": "Expire a Cluster Client Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/cluster_token"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ClusterClientToken UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cluster_client_token.ClusterClientToken"
                        }
                    }
                }
            }
        },
        "/api/v1/cluster_token/{uuid}/refresh": {
            "put": {
                "description": "Refresh Time of a Cluster Client Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/cluster_token"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ClusterClientToken UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cluster_client_token.ClusterClientToken"
                        }
                    }
                }
            }
        },
        "/api/v1/global_variables": {
            "get": {
                "description": "Find GlobalVariables",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/global_variables"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "query  github.com/claion-org/claiflow/pkg/server/database/vanilla/stmt/README.md",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order  github.com/claion-org/claiflow/pkg/server/database/vanilla/stmt/README.md",
                        "name": "o",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/global_variables.GlobalVariable"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/global_variables/{uuid}": {
            "get": {
                "description": "Get a GlobalVariable",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/global_variables"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "GlobalVariable UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/global_variables.GlobalVariable"
                        }
                    }
                }
            },
            "put": {
                "description": "Update GlobalVariable Value",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/global_variables"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "GlobalVariable UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "UpdateValue",
                        "name": "enviroment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/global_variables.UpdateValue"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/global_variables.GlobalVariable"
                        }
                    }
                }
            }
        },
        "/api/v1/service": {
            "get": {
                "description": "Find Services",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/service"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "query  github.com/claion-org/claiflow/pkg/server/database/vanilla/stmt/README.md",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order  github.com/claion-org/claiflow/pkg/server/database/vanilla/stmt/README.md",
                        "name": "o",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "paging github.com/claion-org/claiflow/pkg/server/database/vanilla/stmt/README.md",
                        "name": "p",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.ServiceResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Service (Multi Clusters)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/service"
                ],
                "parameters": [
                    {
                        "description": "Create",
                        "name": "service",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.Create"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.ServiceResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/session": {
            "get": {
                "description": "Find Cluster Client Sessions",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/session"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "query  github.com/claion-org/claiflow/pkg/database/vanilla/stmt/README.md",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order  github.com/claion-org/claiflow/pkg/database/vanilla/stmt/README.md",
                        "name": "o",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "paging github.com/claion-org/claiflow/pkg/database/vanilla/stmt/README.md",
                        "name": "p",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cluster_client_session.ClusterClientSession"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/session/alive": {
            "get": {
                "description": "Check Alive a Cluster Client Session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/session"
                ],
                "deprecated": true,
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster UUID",
                        "name": "cluster_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cluster.ClusterClientSessionStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/session/{uuid}": {
            "get": {
                "description": "Get a Cluster Client Session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/session"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ClusterClientSession UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cluster_client_session.ClusterClientSession"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a Cluster Client Session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/session"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ClusterClientSession UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/webhook": {
            "get": {
                "description": "Find webhooks",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/webhook"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "query  github.com/claion-org/claiflow/pkg/server/database/vanilla/stmt/README.md",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order  github.com/claion-org/claiflow/pkg/server/database/vanilla/stmt/README.md",
                        "name": "o",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "paging github.com/claion-org/claiflow/pkg/server/database/vanilla/stmt/README.md",
                        "name": "p",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/webhook.Webhook"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a webhook",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/webhook"
                ],
                "parameters": [
                    {
                        "description": "Create",
                        "name": "webhook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhook.Create"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webhook.Webhook"
                        }
                    }
                }
            }
        },
        "/api/v1/webhook/{uuid}": {
            "get": {
                "description": "Get a webhook",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/webhook"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "webhook UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webhook.Webhook"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a webhook",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/webhook"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Webhook UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update",
                        "name": "webhook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhook.Update"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webhook.Webhook"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a webhook",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/webhook"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Webhook UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/webhook/{uuid}/publish": {
            "post": {
                "description": "Publish a webhook message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v1/webhook"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "webhook UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Publish message",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "client.Auth": {
            "type": "object",
            "properties": {
                "assertion": {
                    "type": "string"
                },
                "client_lib_version": {
                    "type": "string"
                },
                "client_version": {
                    "type": "string"
                },
                "cluster_uuid": {
                    "type": "string"
                }
            }
        },
        "client.ServiceResponse": {
            "type": "object",
            "properties": {
                "cluster_uuid": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                },
                "flow": {
                    "type": "string"
                },
                "inputs": {
                    "type": "object"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "step_max": {
                    "type": "integer"
                },
                "subscribed_channel": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "template_uuid": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "client.ServiceStatus": {
            "type": "object",
            "properties": {
                "ended": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                },
                "started": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "cluster.Cluster": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "cluster.ClusterClientSessionStatus": {
            "type": "object",
            "properties": {
                "alive": {
                    "type": "boolean"
                },
                "clientLibVersion": {
                    "type": "string"
                },
                "clientVersion": {
                    "type": "string"
                }
            }
        },
        "cluster.Create": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "summary": {
                    "description": "(optional)",
                    "type": "string"
                },
                "uuid": {
                    "description": "(optional)",
                    "type": "string"
                }
            }
        },
        "cluster.Update": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "(optional)",
                    "type": "string"
                },
                "summary": {
                    "description": "(optional)",
                    "type": "string"
                }
            }
        },
        "cluster_client_session.ClusterClientSession": {
            "type": "object",
            "properties": {
                "cluster_uuid": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                },
                "deleted": {
                    "type": "string"
                },
                "expiration_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "issued_at_time": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "cluster_client_token.ClusterClientToken": {
            "type": "object",
            "properties": {
                "cluster_uuid": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                },
                "expiration_time": {
                    "type": "string"
                },
                "issued_at_time": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "cluster_client_token.Create": {
            "type": "object",
            "properties": {
                "cluster_uuid": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "summary": {
                    "description": "(optional)",
                    "type": "string"
                },
                "token": {
                    "description": "(optional)",
                    "type": "string"
                },
                "uuid": {
                    "description": "(optional)",
                    "type": "string"
                }
            }
        },
        "cluster_client_token.Update": {
            "type": "object",
            "properties": {
                "expiration_time": {
                    "description": "(optional)",
                    "type": "string"
                },
                "issued_at_time": {
                    "description": "(optional)",
                    "type": "string"
                },
                "name": {
                    "description": "(optional)",
                    "type": "string"
                },
                "summary": {
                    "description": "(optional)",
                    "type": "string"
                },
                "token": {
                    "description": "(optional)",
                    "type": "string"
                }
            }
        },
        "global_variables.GlobalVariable": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "summary": {
                    "description": "(optional)",
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "global_variables.UpdateValue": {
            "type": "object",
            "properties": {
                "value": {
                    "description": "(optional)",
                    "type": "string"
                }
            }
        },
        "service.Create": {
            "type": "object",
            "properties": {
                "inputs": {
                    "$ref": "#/definitions/service.Object"
                },
                "name": {
                    "type": "string"
                },
                "subscribed_channel": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "template_uuid": {
                    "type": "string"
                },
                "uuid": {
                    "description": "(optional)",
                    "type": "string"
                }
            }
        },
        "service.Object": {
            "type": "object",
            "additionalProperties": {}
        },
        "service.ResultResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "save_type": {
                    "type": "integer"
                }
            }
        },
        "service.ServiceResponse": {
            "type": "object",
            "properties": {
                "cluster_uuid": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                },
                "flow": {
                    "type": "string"
                },
                "inputs": {
                    "type": "object"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ResultResponse"
                    }
                },
                "statuses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.StatusResponse"
                    }
                },
                "step_max": {
                    "type": "integer"
                },
                "subscribed_channel": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "template_uuid": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "service.StatusResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "ended": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "started": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "step_seq": {
                    "type": "integer"
                }
            }
        },
        "webhook.Create": {
            "type": "object",
            "properties": {
                "conditionFilter": {
                    "description": "(optional)",
                    "type": "string"
                },
                "conditionValidator": {
                    "description": "(optional)",
                    "type": "string"
                },
                "headers": {
                    "description": "(optional)",
                    "$ref": "#/definitions/webhook.Header"
                },
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "summary": {
                    "description": "(optional)",
                    "type": "string"
                },
                "timeout": {
                    "description": "(optional)",
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "uuid": {
                    "description": "(optional)",
                    "type": "string"
                }
            }
        },
        "webhook.Header": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        },
        "webhook.Update": {
            "type": "object",
            "properties": {
                "conditionFilter": {
                    "description": "(optional)",
                    "type": "string"
                },
                "conditionValidator": {
                    "description": "(optional)",
                    "type": "string"
                },
                "headers": {
                    "description": "(optional)",
                    "$ref": "#/definitions/webhook.Header"
                },
                "method": {
                    "description": "(optional)",
                    "type": "string"
                },
                "name": {
                    "description": "(optional)",
                    "type": "string"
                },
                "summary": {
                    "description": "(optional)",
                    "type": "string"
                },
                "timeout": {
                    "description": "(optional)",
                    "type": "string"
                },
                "url": {
                    "description": "(optional)",
                    "type": "string"
                }
            }
        },
        "webhook.Webhook": {
            "type": "object",
            "properties": {
                "conditionFilter": {
                    "type": "string"
                },
                "conditionValidator": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                },
                "headers": {
                    "type": "object"
                },
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "timeout": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ClientAuthorization": {
            "description": "Bearer token for client api",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "CLAIFLOW",
	Description:      "this is a claiflow server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
