// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v3.21.12
// source: pkg/server/api/datatype/nullable.proto

package datatype

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NullString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	String_ string `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
	Valid   bool   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *NullString) Reset() {
	*x = NullString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullString) ProtoMessage() {}

func (x *NullString) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullString.ProtoReflect.Descriptor instead.
func (*NullString) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_datatype_nullable_proto_rawDescGZIP(), []int{0}
}

func (x *NullString) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *NullString) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type NullBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bool  bool `protobuf:"varint,1,opt,name=bool,proto3" json:"bool,omitempty"`
	Valid bool `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *NullBool) Reset() {
	*x = NullBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullBool) ProtoMessage() {}

func (x *NullBool) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullBool.ProtoReflect.Descriptor instead.
func (*NullBool) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_datatype_nullable_proto_rawDescGZIP(), []int{1}
}

func (x *NullBool) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *NullBool) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type NullTimestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Valid     bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *NullTimestamp) Reset() {
	*x = NullTimestamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullTimestamp) ProtoMessage() {}

func (x *NullTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullTimestamp.ProtoReflect.Descriptor instead.
func (*NullTimestamp) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_datatype_nullable_proto_rawDescGZIP(), []int{2}
}

func (x *NullTimestamp) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *NullTimestamp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type NullDuration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration *durationpb.Duration `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Valid    bool                 `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *NullDuration) Reset() {
	*x = NullDuration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullDuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullDuration) ProtoMessage() {}

func (x *NullDuration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullDuration.ProtoReflect.Descriptor instead.
func (*NullDuration) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_datatype_nullable_proto_rawDescGZIP(), []int{3}
}

func (x *NullDuration) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *NullDuration) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type NullInt32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Int32 int32 `protobuf:"varint,1,opt,name=int32,proto3" json:"int32,omitempty"`
	Valid bool  `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *NullInt32) Reset() {
	*x = NullInt32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullInt32) ProtoMessage() {}

func (x *NullInt32) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullInt32.ProtoReflect.Descriptor instead.
func (*NullInt32) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_datatype_nullable_proto_rawDescGZIP(), []int{4}
}

func (x *NullInt32) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *NullInt32) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type NullInt64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Int64 int64 `protobuf:"varint,1,opt,name=int64,proto3" json:"int64,omitempty"`
	Valid bool  `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *NullInt64) Reset() {
	*x = NullInt64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullInt64) ProtoMessage() {}

func (x *NullInt64) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullInt64.ProtoReflect.Descriptor instead.
func (*NullInt64) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_datatype_nullable_proto_rawDescGZIP(), []int{5}
}

func (x *NullInt64) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

func (x *NullInt64) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type NullUint32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uint32 uint32 `protobuf:"varint,1,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Valid  bool   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *NullUint32) Reset() {
	*x = NullUint32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullUint32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullUint32) ProtoMessage() {}

func (x *NullUint32) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullUint32.ProtoReflect.Descriptor instead.
func (*NullUint32) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_datatype_nullable_proto_rawDescGZIP(), []int{6}
}

func (x *NullUint32) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

func (x *NullUint32) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type NullUint64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uint64 uint64 `protobuf:"varint,1,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Valid  bool   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *NullUint64) Reset() {
	*x = NullUint64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullUint64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullUint64) ProtoMessage() {}

func (x *NullUint64) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullUint64.ProtoReflect.Descriptor instead.
func (*NullUint64) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_datatype_nullable_proto_rawDescGZIP(), []int{7}
}

func (x *NullUint64) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

func (x *NullUint64) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type NullFloat32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Float32 float32 `protobuf:"fixed32,1,opt,name=float32,proto3" json:"float32,omitempty"`
	Valid   bool    `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *NullFloat32) Reset() {
	*x = NullFloat32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullFloat32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullFloat32) ProtoMessage() {}

func (x *NullFloat32) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullFloat32.ProtoReflect.Descriptor instead.
func (*NullFloat32) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_datatype_nullable_proto_rawDescGZIP(), []int{8}
}

func (x *NullFloat32) GetFloat32() float32 {
	if x != nil {
		return x.Float32
	}
	return 0
}

func (x *NullFloat32) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type NullFloat64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Float64 float64 `protobuf:"fixed64,1,opt,name=float64,proto3" json:"float64,omitempty"`
	Valid   bool    `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *NullFloat64) Reset() {
	*x = NullFloat64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullFloat64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullFloat64) ProtoMessage() {}

func (x *NullFloat64) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_datatype_nullable_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullFloat64.ProtoReflect.Descriptor instead.
func (*NullFloat64) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_datatype_nullable_proto_rawDescGZIP(), []int{9}
}

func (x *NullFloat64) GetFloat64() float64 {
	if x != nil {
		return x.Float64
	}
	return 0
}

func (x *NullFloat64) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_pkg_server_api_datatype_nullable_proto protoreflect.FileDescriptor

var file_pkg_server_api_datatype_nullable_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x64, 0x61, 0x74, 0x61, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x70, 0x6b, 0x67, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x74, 0x79, 0x70,
	0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x0a, 0x4e, 0x75, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x34,
	0x0a, 0x08, 0x4e, 0x75, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x22, 0x5f, 0x0a, 0x0d, 0x4e, 0x75, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x5b, 0x0a, 0x0c, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x22, 0x37, 0x0a, 0x09, 0x4e, 0x75, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x09, 0x4e,
	0x75, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x36,
	0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x22, 0x3a, 0x0a, 0x0a, 0x4e, 0x75, 0x6c, 0x6c, 0x55, 0x69, 0x6e, 0x74,
	0x33, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x22, 0x3a, 0x0a, 0x0a, 0x4e, 0x75, 0x6c, 0x6c, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x0b,
	0x4e, 0x75, 0x6c, 0x6c, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x12, 0x18, 0x0a, 0x07, 0x66,
	0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x66, 0x6c,
	0x6f, 0x61, 0x74, 0x33, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x0b, 0x4e,
	0x75, 0x6c, 0x6c, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6c,
	0x6f, 0x61, 0x74, 0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x66, 0x6c, 0x6f,
	0x61, 0x74, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x61, 0x69, 0x6f, 0x6e, 0x2d,
	0x6f, 0x72, 0x67, 0x2f, 0x63, 0x6c, 0x61, 0x69, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61,
	0x74, 0x79, 0x70, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_server_api_datatype_nullable_proto_rawDescOnce sync.Once
	file_pkg_server_api_datatype_nullable_proto_rawDescData = file_pkg_server_api_datatype_nullable_proto_rawDesc
)

func file_pkg_server_api_datatype_nullable_proto_rawDescGZIP() []byte {
	file_pkg_server_api_datatype_nullable_proto_rawDescOnce.Do(func() {
		file_pkg_server_api_datatype_nullable_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_server_api_datatype_nullable_proto_rawDescData)
	})
	return file_pkg_server_api_datatype_nullable_proto_rawDescData
}

var file_pkg_server_api_datatype_nullable_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_server_api_datatype_nullable_proto_goTypes = []interface{}{
	(*NullString)(nil),            // 0: pkg.server.api.datatype.NullString
	(*NullBool)(nil),              // 1: pkg.server.api.datatype.NullBool
	(*NullTimestamp)(nil),         // 2: pkg.server.api.datatype.NullTimestamp
	(*NullDuration)(nil),          // 3: pkg.server.api.datatype.NullDuration
	(*NullInt32)(nil),             // 4: pkg.server.api.datatype.NullInt32
	(*NullInt64)(nil),             // 5: pkg.server.api.datatype.NullInt64
	(*NullUint32)(nil),            // 6: pkg.server.api.datatype.NullUint32
	(*NullUint64)(nil),            // 7: pkg.server.api.datatype.NullUint64
	(*NullFloat32)(nil),           // 8: pkg.server.api.datatype.NullFloat32
	(*NullFloat64)(nil),           // 9: pkg.server.api.datatype.NullFloat64
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 11: google.protobuf.Duration
}
var file_pkg_server_api_datatype_nullable_proto_depIdxs = []int32{
	10, // 0: pkg.server.api.datatype.NullTimestamp.timestamp:type_name -> google.protobuf.Timestamp
	11, // 1: pkg.server.api.datatype.NullDuration.duration:type_name -> google.protobuf.Duration
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_server_api_datatype_nullable_proto_init() }
func file_pkg_server_api_datatype_nullable_proto_init() {
	if File_pkg_server_api_datatype_nullable_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_server_api_datatype_nullable_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_server_api_datatype_nullable_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_server_api_datatype_nullable_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullTimestamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_server_api_datatype_nullable_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullDuration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_server_api_datatype_nullable_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullInt32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_server_api_datatype_nullable_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullInt64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_server_api_datatype_nullable_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullUint32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_server_api_datatype_nullable_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullUint64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_server_api_datatype_nullable_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullFloat32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_server_api_datatype_nullable_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullFloat64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_server_api_datatype_nullable_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_server_api_datatype_nullable_proto_goTypes,
		DependencyIndexes: file_pkg_server_api_datatype_nullable_proto_depIdxs,
		MessageInfos:      file_pkg_server_api_datatype_nullable_proto_msgTypes,
	}.Build()
	File_pkg_server_api_datatype_nullable_proto = out.File
	file_pkg_server_api_datatype_nullable_proto_rawDesc = nil
	file_pkg_server_api_datatype_nullable_proto_goTypes = nil
	file_pkg_server_api_datatype_nullable_proto_depIdxs = nil
}
