apiVersion: v1
kind: ServiceAccount
metadata:
  name: claiflowclient-controller
  namespace: claiflowclient
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: claiflowclient-controller
rules:
  # for helm install, uninstall, prometheus-operator
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["/metrics", "/metrics/cadvisor"] # '*' in a nonResourceURL is a suffix glob match
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: claiflowclient-controller
subjects:
  - kind: ServiceAccount
    name: claiflowclient-controller
    namespace: claiflowclient
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: claiflowclient-controller