// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v3.21.12
// source: pkg/server/api/client/auth.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterUuid      string `protobuf:"bytes,1,opt,name=clusterUuid,proto3" json:"clusterUuid,omitempty"`
	Assertion        string `protobuf:"bytes,2,opt,name=assertion,proto3" json:"assertion,omitempty"`
	ClientVersion    string `protobuf:"bytes,3,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	ClientLibVersion string `protobuf:"bytes,4,opt,name=clientLibVersion,proto3" json:"clientLibVersion,omitempty"`
}

func (x *AuthRequestV1) Reset() {
	*x = AuthRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_server_api_client_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequestV1) ProtoMessage() {}

func (x *AuthRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_client_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequestV1.ProtoReflect.Descriptor instead.
func (*AuthRequestV1) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_client_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequestV1) GetClusterUuid() string {
	if x != nil {
		return x.ClusterUuid
	}
	return ""
}

func (x *AuthRequestV1) GetAssertion() string {
	if x != nil {
		return x.Assertion
	}
	return ""
}

func (x *AuthRequestV1) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *AuthRequestV1) GetClientLibVersion() string {
	if x != nil {
		return x.ClientLibVersion
	}
	return ""
}

type AuthResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthResponseV1) Reset() {
	*x = AuthResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_server_api_client_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponseV1) ProtoMessage() {}

func (x *AuthResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_server_api_client_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponseV1.ProtoReflect.Descriptor instead.
func (*AuthResponseV1) Descriptor() ([]byte, []int) {
	return file_pkg_server_api_client_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponseV1) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_pkg_server_api_client_auth_proto protoreflect.FileDescriptor

var file_pkg_server_api_client_auth_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x15, 0x70, 0x6b, 0x67, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0xa2, 0x01, 0x0a, 0x0e, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x76, 0x31, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x73, 0x73, 0x65, 0x72, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x72, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x62, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x62, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x27,
	0x0a, 0x0f, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x76,
	0x31, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x61, 0x69, 0x6f, 0x6e, 0x2d, 0x6f, 0x72, 0x67,
	0x2f, 0x63, 0x6c, 0x61, 0x69, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_server_api_client_auth_proto_rawDescOnce sync.Once
	file_pkg_server_api_client_auth_proto_rawDescData = file_pkg_server_api_client_auth_proto_rawDesc
)

func file_pkg_server_api_client_auth_proto_rawDescGZIP() []byte {
	file_pkg_server_api_client_auth_proto_rawDescOnce.Do(func() {
		file_pkg_server_api_client_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_server_api_client_auth_proto_rawDescData)
	})
	return file_pkg_server_api_client_auth_proto_rawDescData
}

var file_pkg_server_api_client_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_server_api_client_auth_proto_goTypes = []interface{}{
	(*AuthRequestV1)(nil),  // 0: pkg.server.api.client.AuthRequest_v1
	(*AuthResponseV1)(nil), // 1: pkg.server.api.client.AuthResponse_v1
}
var file_pkg_server_api_client_auth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_server_api_client_auth_proto_init() }
func file_pkg_server_api_client_auth_proto_init() {
	if File_pkg_server_api_client_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_server_api_client_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_server_api_client_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_server_api_client_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_server_api_client_auth_proto_goTypes,
		DependencyIndexes: file_pkg_server_api_client_auth_proto_depIdxs,
		MessageInfos:      file_pkg_server_api_client_auth_proto_msgTypes,
	}.Build()
	File_pkg_server_api_client_auth_proto = out.File
	file_pkg_server_api_client_auth_proto_rawDesc = nil
	file_pkg_server_api_client_auth_proto_goTypes = nil
	file_pkg_server_api_client_auth_proto_depIdxs = nil
}
