// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: pkg/server/api/client/service.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ClientService_AuthV1_FullMethodName                = "/pkg.server.api.client.ClientService/Auth_v1"
	ClientService_ServicePollingV1_FullMethodName      = "/pkg.server.api.client.ClientService/ServicePolling_v1"
	ClientService_UpdateServiceStatusV1_FullMethodName = "/pkg.server.api.client.ClientService/UpdateServiceStatus_v1"
)

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientServiceClient interface {
	AuthV1(ctx context.Context, in *AuthRequestV1, opts ...grpc.CallOption) (*AuthResponseV1, error)
	ServicePollingV1(ctx context.Context, in *ServicePollingRequestV1, opts ...grpc.CallOption) (*ServicePollingResponseV1, error)
	UpdateServiceStatusV1(ctx context.Context, in *UpdateServiceStatusRequestV1, opts ...grpc.CallOption) (*UpdateServiceStatusResponseV1, error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) AuthV1(ctx context.Context, in *AuthRequestV1, opts ...grpc.CallOption) (*AuthResponseV1, error) {
	out := new(AuthResponseV1)
	err := c.cc.Invoke(ctx, ClientService_AuthV1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) ServicePollingV1(ctx context.Context, in *ServicePollingRequestV1, opts ...grpc.CallOption) (*ServicePollingResponseV1, error) {
	out := new(ServicePollingResponseV1)
	err := c.cc.Invoke(ctx, ClientService_ServicePollingV1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) UpdateServiceStatusV1(ctx context.Context, in *UpdateServiceStatusRequestV1, opts ...grpc.CallOption) (*UpdateServiceStatusResponseV1, error) {
	out := new(UpdateServiceStatusResponseV1)
	err := c.cc.Invoke(ctx, ClientService_UpdateServiceStatusV1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
// All implementations must embed UnimplementedClientServiceServer
// for forward compatibility
type ClientServiceServer interface {
	AuthV1(context.Context, *AuthRequestV1) (*AuthResponseV1, error)
	ServicePollingV1(context.Context, *ServicePollingRequestV1) (*ServicePollingResponseV1, error)
	UpdateServiceStatusV1(context.Context, *UpdateServiceStatusRequestV1) (*UpdateServiceStatusResponseV1, error)
	mustEmbedUnimplementedClientServiceServer()
}

// UnimplementedClientServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClientServiceServer struct {
}

func (UnimplementedClientServiceServer) AuthV1(context.Context, *AuthRequestV1) (*AuthResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthV1 not implemented")
}
func (UnimplementedClientServiceServer) ServicePollingV1(context.Context, *ServicePollingRequestV1) (*ServicePollingResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServicePollingV1 not implemented")
}
func (UnimplementedClientServiceServer) UpdateServiceStatusV1(context.Context, *UpdateServiceStatusRequestV1) (*UpdateServiceStatusResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateServiceStatusV1 not implemented")
}
func (UnimplementedClientServiceServer) mustEmbedUnimplementedClientServiceServer() {}

// UnsafeClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServiceServer will
// result in compilation errors.
type UnsafeClientServiceServer interface {
	mustEmbedUnimplementedClientServiceServer()
}

func RegisterClientServiceServer(s grpc.ServiceRegistrar, srv ClientServiceServer) {
	s.RegisterService(&ClientService_ServiceDesc, srv)
}

func _ClientService_AuthV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).AuthV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_AuthV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).AuthV1(ctx, req.(*AuthRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_ServicePollingV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicePollingRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).ServicePollingV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_ServicePollingV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).ServicePollingV1(ctx, req.(*ServicePollingRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_UpdateServiceStatusV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceStatusRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).UpdateServiceStatusV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_UpdateServiceStatusV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).UpdateServiceStatusV1(ctx, req.(*UpdateServiceStatusRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientService_ServiceDesc is the grpc.ServiceDesc for ClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pkg.server.api.client.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth_v1",
			Handler:    _ClientService_AuthV1_Handler,
		},
		{
			MethodName: "ServicePolling_v1",
			Handler:    _ClientService_ServicePollingV1_Handler,
		},
		{
			MethodName: "UpdateServiceStatus_v1",
			Handler:    _ClientService_UpdateServiceStatusV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/server/api/client/service.proto",
}
